version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: draft_legends_db
    environment:
      POSTGRES_DB: draft_legends
      POSTGRES_USER: draft_legends_user
      POSTGRES_PASSWORD: draft_legends_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
